chute/apps/me/urls.py
# -*- coding: UTF-8 -*-
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from .views import (ConfirmAccountView,
                    ChangePasswordView,

                    ConfirmPasswordChangeRequest,
                    ConfirmEmailChangeRequest,

                    ConfirmEmailValidationRequest,
                    SendEmailValidationRequest,

                    PaymentListView,
                    PlanListView,
                    PlanChangeView,
                    AccountCancelView,
                    WelcomeView,

                    AccountSettingsView,
                    LawyerLetterheadView)


urlpatterns = patterns(
    '',
    url(r'^email_not_validated/$', login_required(TemplateView.as_view(template_name='me/email-validation-pending.html')), name='email-not-validated'),
    url(r'^email_not_validated/send/$', login_required(SendEmailValidationRequest.as_view()), name='send-email-validation-request'),
    url(r'^email_confirmed/(?P<token>.*)/$', ConfirmEmailValidationRequest.as_view(), name='confirm-email-address'),

    url(r'^email_change_confirmed/(?P<token>.*)/$', ConfirmEmailChangeRequest.as_view(), name='confirm-email-change'),
    url(r'^password_change_confirmed/(?P<token>.*)/$', ConfirmPasswordChangeRequest.as_view(), name='confirm-password-change'),

    url(r'^payments/$', login_required(PaymentListView.as_view()), name='payment-list'),
    url(r'^plans/(?P<plan>[a-z0-9_-]{1,25})/$', login_required(PlanChangeView.as_view()), name='plan-change'),
    url(r'^plans/$', login_required(PlanListView.as_view()), name='plan-list'),
    url(r'^welcome/$', login_required(WelcomeView.as_view()), name='welcome'),

    url(r'^settings/letterhead/$', login_required(LawyerLetterheadView.as_view()), name='letterhead'),
    url(r'^settings/confirm/$', login_required(ConfirmAccountView.as_view()), name='confirm-account'),
    url(r'^settings/change-password/$', login_required(ChangePasswordView.as_view()), name='change-password'),

    url(r'^settings/$', login_required(AccountSettingsView.as_view()), name='settings'),

    url(r'^cancel/$', login_required(AccountCancelView.as_view()), name='cancel'),
)

chute/urls.py
from django.conf import settings
#from django.conf.urls.static import static
from chute.static import static
from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),

    url(r'^api/v1/', include('chute.api.urls')),

    url(r'^me/password/', include('password_reset.urls')),
    url(r'^me/', include('chute.apps.me.urls', namespace='me')),

    url(r'^project/', include('chute.apps.project.urls', namespace='project')),
    url(r'^feed/', include('chute.apps.feed.urls', namespace='feed')),
    url(r'^box/', include('chute.apps.box.urls', namespace='box')),

    url(r'^django-rq/', include('django_rq.urls')),

    url(r'^', include('social.apps.django_app.urls', namespace='social')),
    #url(r'^', TemplateView.as_view(template_name='base.html'), name='base'),
    url(r'^', include('chute.apps.public.urls', namespace='public')),
)

# Add the MEDIA_URL to the dev environment
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

chute/apps/me/api/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User

from rest_framework import generics
from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework import status as http_status

from chute.apps.project.models import Project

from ..services import EnsureCollaboratorService
from .serializers import (UserSerializer,
                          CollaboratorSerializer,)


class UserProfileViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    lookup_field = 'email'
    lookup_url_kwarg = 'email'
    filter_fields = ('email', 'username')
    allowed_methods = ('get', 'options', 'head',)


class CollaboratorEndpoint(generics.ListCreateAPIView,
                           generics.RetrieveDestroyAPIView):
    lookup_field = 'slug'
    lookup_url_kwarg = 'slug'
    queryset = Project.objects.all()
    serializer_class = CollaboratorSerializer

    def list(self, request, **kwargs):
        self.project = self.get_object()
        collaborator_serializer = self.get_serializer(self.project.projectcollaborator_set.all(), many=True)
        headers = self.get_success_headers(collaborator_serializer)
        return Response(collaborator_serializer.data, status=http_status.HTTP_200_OK, headers=headers)

    def create(self, request, **kwargs):
        project = self.get_object()
        email = request.POST.get('email')
        first_name = request.POST.get('first_name', None)
        last_name = request.POST.get('last_name', None)
        full_name = '%s %s' % (first_name, last_name)

        service = EnsureCollaboratorService(project=project, email=email, full_name=full_name)
        is_new, user, profile, collaborator, collaborator_is_new = service.process()

        collaborator_serializer = self.get_serializer(project.projectcollaborator_set.all(), many=True)
        headers = self.get_success_headers(collaborator_serializer)

        status = http_status.HTTP_201_CREATED if collaborator_is_new is True else http_status.HTTP_202_ACCEPTED
        return Response(collaborator_serializer.data, status=status, headers=headers)

    # def retrieve(self, request, **kwargs):
    #     import pdb;pdb.set_trace()

    def destroy(self, request, **kwargs):
        project = self.get_object()
        collaborator_record = project.projectcollaborator_set.get(user__email=kwargs.get('email'))
        collaborator_record.delete()

        collaborator_serializer = self.get_serializer(project.projectcollaborator_set.all(), many=True)
        headers = self.get_success_headers(collaborator_serializer)

        return Response(collaborator_serializer.data, status=http_status.HTTP_202_ACCEPTED)

chute/apps/me/views.py
# -*- coding: utf-8 -*-
from django.http import Http404
from django.core import signing
from django.conf import settings
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import redirect
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.core.urlresolvers import reverse_lazy
from django.views.generic import FormView, ListView, UpdateView, TemplateView, RedirectView
from django.views.generic.edit import BaseUpdateView
from django.shortcuts import get_object_or_404

from payments.models import Charge, Customer

from chute.apps.me.signals import send_welcome_email
#from chute.mixins import AjaxFormView, AjaxModelFormView, ModalView

from .models import UserProfile

from .mailers import ValidateEmailMailer

from .forms import (ConfirmAccountForm,
                    ChangePasswordForm,
                    AccountSettingsForm,
                    LawyerLetterheadForm,
                    PlanChangeForm,
                    AccountCancelForm)

import json

import logging
logger = logging.getLogger('django.request')


class ConfirmAccountView(UpdateView):
    form_class = ConfirmAccountForm
    model = User
    template_name = 'user/settings/account.html'

    def dispatch(self, request, *args, **kwargs):

        # check to see if they have already set their password
        if request.user.is_authenticated() and request.user.password not in [None, '', '!']:
            messages.warning(request, 'It looks like you have already confirmed your account. No need to access that form.')
            return redirect(reverse('public:home'))

        return super(ConfirmAccountView, self).dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        return self.request.user

    def get_form_kwargs(self):
        kwargs = super(ConfirmAccountView, self).get_form_kwargs()
        kwargs.update({
            'request': self.request
        })
        return kwargs

    def form_valid(self, form):
        # get target user, profile
        profile = self.request.user.profile

        # if user is new, has not set password
        sent_welcome_email = profile.data.get('sent_welcome_email', False)
        if sent_welcome_email is False:
            #
            # Send welcome email
            #
            send_welcome_email.send(sender=self.request.user._meta.model, instance=self.request.user, created=True)

            # store the json reciept
            profile.data['sent_welcome_email'] = True
            profile.save(update_fields=['data'])

        return super(ConfirmAccountView, self).form_valid(form)

    def get_success_url(self):
        messages.success(self.request, 'Thank you. You have confirmed your account')
        try:
            first_invite_key = self.request.user.invitations.all().first()
            return first_invite_key.next

        except AttributeError:
            # was no invite key
            return reverse_lazy('public:home')


class SendEmailValidationRequest(BaseUpdateView):
    def post(self, request, *args, **kwargs):
        """
        Jsut send it; if the user has already validated then we will catch that
        on the confirmation view
        """
        mailer = ValidateEmailMailer(((request.user.get_full_name(), request.user.email,),))
        mailer.process(user=request.user)

        content = {
            'detail': 'Email sent'
        }
        return HttpResponse(json.dumps(content), content_type='application/json', **kwargs)


# ------------------------------------------
# Start Settings Change Confirmation Views
# ------------------------------------------


class BaseConfirmValidationRequest(RedirectView):
    url = '/'  # redirect to home

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        self.args = args
        self.kwargs = kwargs

        self.user = self.get_user(token=kwargs.get('token'))
        self.profile = self.user.profile

        self.save()
        return super(BaseConfirmValidationRequest, self).dispatch(request=request, *args, **kwargs)

    def get_user(self, token):
        try:
            pk = signing.loads(token, salt=settings.URL_ENCODE_SECRET_KEY)
        except signing.BadSignature:
            raise Http404
        return get_object_or_404(User, pk=pk)

    def save(self):
        raise NotImplementedError


class ConfirmEmailValidationRequest(BaseConfirmValidationRequest):

    def save(self):
        self.profile.validated_email = True
        self.profile.save(update_fields=['data'])

        messages.success(self.request, 'Thanks. You have confirmed your email address.')
        logger.info(u'User: %s has validated their email' % self.user)


class ConfirmEmailChangeRequest(BaseConfirmValidationRequest):
    """
    When a user confirms that they want to change their email they come
    here and it does that for them.
    """

    def save(self):
        email = self.profile.data.get('validation_required_temp_email', False)
        original_email = self.user.email

        if email and email is not False:
            self.user.email = email
            self.user.save(update_fields=['email'])

            # remove temp password
            del self.profile.data['validation_required_temp_email']
            # set validated_email to True
            self.profile.validated_email = True
            self.profile.save(update_fields=['data'])

        messages.success(self.request, 'Congratulations. Your email has been changed. Please login with your new email.')
        logger.info(u'User: %s has confirmed their change of email address from: %s to: %s' % (self.user, original_email, self.user.email))


class ConfirmPasswordChangeRequest(BaseConfirmValidationRequest):
    """
    When a user confirms that they want to change their password they come
    here and it does that for them.
    """

    def save(self):
        password = self.profile.data.get('validation_required_temp_password', False)

        if password and password is not False:
            self.user.password = password
            self.user.save(update_fields=['password'])
            # remove temp password
            del self.profile.data['validation_required_temp_password']
            self.profile.save(update_fields=['data'])

        messages.success(self.request, 'Congratulations. Your password has been changed. Please login with your new password.')
        logger.info(u'User: %s has confirmed their change of password' % self.user)

# ----------------------------
# End Confirmation Views
# ----------------------------


class AccountSettingsView(UpdateView):
    form_class = AccountSettingsForm
    model = User
    success_url = reverse_lazy('me:settings')
    template_name = 'user/settings/account.html'

    def get_form_kwargs(self):
        kwargs = super(AccountSettingsView, self).get_form_kwargs()
        kwargs.update({
            'request': self.request
        })
        return kwargs

    def get_object(self, queryset=None):
        return self.request.user


#class ChangePasswordView(AjaxModelFormView, FormView):
class ChangePasswordView(FormView):
    form_class = ChangePasswordForm
    success_url = reverse_lazy('me:settings')
    template_name = 'user/settings/change-password.html'

    def get_form_kwargs(self):
        kwargs = super(ChangePasswordView, self).get_form_kwargs()
        kwargs.update({
            'request': self.request,
            'user': self.request.user
        })
        return kwargs


class LawyerLetterheadView(UpdateView):
    """
    View that handles the Letterhead Setup Form for Lawyers
    get the initial form data form the users profile.data
    form will save that data
    """
    form_class = LawyerLetterheadForm
    model = UserProfile
    template_name = 'lawyer/lawyerletterhead_form.html'

    def get_object(self, queryset=None):
        return self.request.user.profile

    def get_initial(self):
        kwargs = super(LawyerLetterheadView, self).get_initial()

        profile = self.request.user.profile

        kwargs.update({
            'firm_name': profile.data.get('firm_name'),
            'firm_address': profile.data.get('firm_address'),
            'firm_logo': profile.data.get('firm_logo'),
        })
        return kwargs

    def get_success_url(self):
        if 'next' in self.request.GET:
            return self.request.GET.get('next')
        else:
            return self.object.get_absolute_url() if self.object is not None and hasattr(self.object, 'get_absolute_url') else reverse('matter:list')

    def get_form_kwargs(self):
        kwargs = super(LawyerLetterheadView, self).get_form_kwargs()
        kwargs.update({
            'user': self.request.user
        })
        return kwargs


class PaymentListView(ListView):
    template_name = 'payments/payment_list.html'

    def get_queryset(self):
        try:
            return Charge.objects.filter(customer=self.request.user.customer).order_by('-created_at')
        except Customer.DoesNotExist:
            return Charge.objects.none()


class PlanListView(TemplateView):
    template_name = 'payments/plan_list.html'

    def get_context_data(self, **kwargs):
        context = super(PlanListView, self).get_context_data(**kwargs)
        context.update({
            'object_list': [settings.PAYMENTS_PLANS['early-bird-monthly'],]
        })
        return context


#class PlanChangeView(ModalView, AjaxFormView, FormView):
class PlanChangeView(FormView):
    form_class = PlanChangeForm
    template_name = 'payments/plan_change.html'

    def get_initial(self):
        return {
            'plan': self.kwargs.get('plan', None)
        }

    def form_valid(self, form):
        form.save()
        return super(PlanChangeView, self).form_valid(form)

    def get_object(self, **kwargs):
        slug = self.kwargs.get('plan', None)
        try:

chute/apps/me/templates/user/settings/account.html
{% extends 'user/base.html' %}

{% load url from future %}{% load crispy_forms_tags %}

{% block page_title %}Settings — {{ block.super }}{% endblock%}

{% block header %}{% endblock %}

{% block body %}


<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
  <li class="active"><a href="#home" role="tab" data-toggle="tab">Account Settings</a></li>
  <li><a href="#profile" role="tab" data-toggle="tab">Integrations</a></li>
  <li><a href="#billing" role="tab" data-toggle="tab">Billing</a></li>
  <li><a href="#cancellation" role="tab" data-toggle="tab">Cancellation</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">

    <div class="tab-pane fade in active" id="home">

          <div class="content-header notifications-header clearfix">
              <div class="container">
                  <div class="col-sm-6 col-sm-offset-3">
                      <h3>Account Settings<br/><small>Manage your account settings</small></h3>
                  </div>
              </div>
          </div>
          <div class="container">
              <div class="col-sm-6 col-sm-offset-3" role="main">
                  {% crispy form %}
              </div>
          </div>

    </div>


    <div class="tab-pane fade" id="profile">

        <div class="content-header notifications-header clearfix">
            <div class="container">
                <div class="col-sm-6 col-sm-offset-3">
                    <h3>Integrations<br/><small>Connect your Revision.com account with 3rd Parties</small></h3>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="col-sm-6 col-sm-offset-3" role="main">
              <ul class="list-group">
                <li>No integrations possible</li>
              </ul>

            </div>
        </div>

    </div>

    <div class="tab-pane fade" id="billing">

        <div class="content-header notifications-header clearfix">
            <div class="container">
                <div class="col-sm-6 col-sm-offset-3">
                    <h3>Billing<br/><small>Plans &amp; Payments</small></h3>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="col-sm-6 col-sm-offset-3" role="main">
              <ul class="list-group">
                <li><a href="{% url 'me:plan-list' %}">Plans</a></li>
                <li><a href="{% url 'me:payment-list' %}">Payments</a></li>
              </ul>
            </div>
        </div>

    </div>

    <div class="tab-pane fade" id="cancellation">

        <div class="content-header notifications-header clearfix">
            <div class="container">
                <div class="col-sm-6 col-sm-offset-3">
                    <h3>Cancellation<br/><small>So you've decided to leave us, please let us know why so that we can try to fix the problem.</small></h3>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="col-sm-6 col-sm-offset-3" role="main">
                <a href="{% url 'me:cancel' %}" class="btn btn-warning" data-toggle="modal" data-target="#cancel-account">Cancel my account</a>
            </div>
        </div>

    </div>

</div>


{% endblock %}

{% block modals %}
    {{ block.super }}
    <div class="modal" id="change-password"></div>
    <div class="modal" id="cancel-account"></div>
{% endblock %}

{% block css %}
    {{ block.super }}
    {{ form.media.css }}
<style>
.tab-content{
  border:0px;
  margin:0px;
  padding:0px;
}
</style>
{% endblock %}

{% block js %}
    {{ block.super }}
    {{ form.media.js }}
    <script>
    'use strict';
    $('a.social-disconnect').on("click", function() {
        var self = $(this);
        var data = $(this).data();

        $.ajax({
          "type": 'POST',
          "url": self.attr('href'),
          "data": {},
          "dataType": 'json',
          "contentType": 'application/json',
          "beforeSend": function (jqXHR, settings) {
              // Pull the token out of the DOM.
              jqXHR.setRequestHeader('X-CSRFToken', $('input[name=csrfmiddlewaretoken]:first').val());
          },
          "complete": function ( data ) {
              document.location.reload();
          }
        });

        return false; //this is critical to stop the click event which will trigger a normal file download!
    });
    </script>
{% endblock %}

chute/apps/me/templates/user/settings/change-password.html
{% extends 'modal.html' %}

{% load crispy_forms_tags %}

{% block modal_title %}Change your password{% endblock %}

{% block content %}
    {% crispy form %}
{% endblock %}