chute/apps/box/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from .views import (BoxList, BoxCreate, BoxEdit, BoxDetail,)


urlpatterns = patterns('',
    url(r'^/(?P<slug>[\d\w\-\_]+)/edit/$', BoxEdit.as_view(), name='edit'),
    url(r'^/(?P<slug>[\d\w\-\_]+)/$', BoxDetail.as_view(), name='detail'),
    url(r'^/create/$', BoxCreate.as_view(), name='create'),
    url(r'^$', BoxList.as_view(), name='list'),
)

chute/apps/me/urls.py
# -*- coding: UTF-8 -*-
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from .views import (ConfirmAccountView,
                    ChangePasswordView,

                    ConfirmPasswordChangeRequest,
                    ConfirmEmailChangeRequest,

                    ConfirmEmailValidationRequest,
                    SendEmailValidationRequest,

                    PaymentListView,
                    PlanListView,
                    PlanChangeView,
                    AccountCancelView,
                    WelcomeView,

                    AccountSettingsView,
                    LawyerLetterheadView)


urlpatterns = patterns(
    '',
    url(r'^email_not_validated/$', login_required(TemplateView.as_view(template_name='me/email-validation-pending.html')), name='email-not-validated'),
    url(r'^email_not_validated/send/$', login_required(SendEmailValidationRequest.as_view()), name='send-email-validation-request'),
    url(r'^email_confirmed/(?P<token>.*)/$', ConfirmEmailValidationRequest.as_view(), name='confirm-email-address'),

    url(r'^email_change_confirmed/(?P<token>.*)/$', ConfirmEmailChangeRequest.as_view(), name='confirm-email-change'),
    url(r'^password_change_confirmed/(?P<token>.*)/$', ConfirmPasswordChangeRequest.as_view(), name='confirm-password-change'),

    url(r'^payments/$', login_required(PaymentListView.as_view()), name='payment-list'),
    url(r'^plans/(?P<plan>[a-z0-9_-]{1,25})/$', login_required(PlanChangeView.as_view()), name='plan-change'),
    url(r'^plans/$', login_required(PlanListView.as_view()), name='plan-list'),
    url(r'^welcome/$', login_required(WelcomeView.as_view()), name='welcome'),

    url(r'^settings/letterhead/$', login_required(LawyerLetterheadView.as_view()), name='letterhead'),
    url(r'^settings/confirm/$', login_required(ConfirmAccountView.as_view()), name='confirm-account'),
    url(r'^settings/change-password/$', login_required(ChangePasswordView.as_view()), name='change-password'),

    url(r'^settings/$', login_required(AccountSettingsView.as_view()), name='settings'),

    url(r'^cancel/$', login_required(AccountCancelView.as_view()), name='cancel'),
)

chute/urls.py
from django.conf import settings
#from django.conf.urls.static import static
from chute.static import static
from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),

    url(r'^api/v1/', include('chute.api.urls')),

    url(r'^me/password/', include('password_reset.urls')),
    url(r'^me/', include('chute.apps.me.urls', namespace='me')),

    url(r'^project/', include('chute.apps.project.urls', namespace='project')),
    url(r'^feed/', include('chute.apps.feed.urls', namespace='feed')),
    url(r'^box/', include('chute.apps.box.urls', namespace='box')),

    url(r'^django-rq/', include('django_rq.urls')),

    url(r'^', include('social.apps.django_app.urls', namespace='social')),
    #url(r'^', TemplateView.as_view(template_name='base.html'), name='base'),
    url(r'^', include('chute.apps.public.urls', namespace='public')),
)

# Add the MEDIA_URL to the dev environment
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load compressed %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% block page_description %}{% endblock %}">
    <meta name="author" content="{% block page_author %}{% endblock %}">
    <link rel="icon" href="/favicon.ico">

    <title>{% block page_title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    {% compressed_css 'base' %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      {% compressed_js 'base_ie_only' %}
    <![endif]-->
    {% block css %}{% endblock css %}
  </head>

  <body>

    {% block navigation %}
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Chute</a>
        </div>

        <ul class="nav navbar-nav">
            <!-- <li><a href="#">Settings</a></li>
            <li><a href="#">Account</a></li> -->
            {% if user.is_authenticated %}
                <li class="active"><a href="{% url 'project:list' %}">Projects</a></li>
                <li><a href="{% url 'me:settings' %}">Account</a></li>
                <li><a href="{% url 'public:logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'public:signin' %}">Sign in</a></li>
                <li><a href="{% url 'public:signup' %}">Sign up</a></li>
            {% endif %}
        </ul>
      </div>
    </nav>
    <div class="row">&nbsp;</div>
    {% endblock %}

    <div class="container">
    {% block jumbo %}{% endblock %}
    {% block body %}
    {% block content %}{% endblock %}
    {% endblock %}
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/sugar/1.4.1/sugar.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/fuse.js/1.1.7/fuse.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.2/moment.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/mousetrap/1.4.6/mousetrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/holder/2.4.0/holder.js"></script>
    <script src="//releases.flowplayer.org/5.5.0/flowplayer.js"></script>

    {% compressed_js 'base' %}
    {% compressed_js 'resources' %}
    {% compressed_js 'react' %}
    {% if debug %}<script src="{{ STATIC_URL }}js/reactjs/0.12.1/JSXTransformer.js"></script>{% endif %}

    {% block js %}{% endblock %}
    <script>
    'use strict';
    $(document).ready(function () {
        $('form[data-parsley-validate]').parsley();
    });
    </script>
  </body>
</html>

templates/footer.html
{% load staticfiles %}
<footer>
    <div class="container">
        <a href="#" class="scrollpoint sp-effect3">
            <img src="{% static 'img/freeze/logo.png' %}" alt="" class="logo">
        </a>
        <div class="social">
            <a href="#" class="scrollpoint sp-effect3"><i class="fa fa-twitter fa-lg"></i></a>
            <a href="#" class="scrollpoint sp-effect3"><i class="fa fa-google-plus fa-lg"></i></a>
            <a href="#" class="scrollpoint sp-effect3"><i class="fa fa-facebook fa-lg"></i></a>
        </div>
        <div class="rights">
            <p>Copyright &copy; 2014</p>
            <p>Template by <a href="http://www.scoopthemes.com" target="_blank">ScoopThemes</a></p>
        </div>
    </div>
</footer>

templates/nav.html
{% load staticfiles %}
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="fa fa-bars fa-lg"></span>
                </button>
                <a class="navbar-brand" href="/">
                    <img src="{% static 'img/freeze/logo.png' %}" alt="" class="logo">
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'project:list' %}">projects</a>
                    </li>
                    <li><a href="#support">support</a>
                    </li>
                    <li><a href="{% url 'public:logout' %}">sign out</a>
                    </li>
                    {% else %}
                    <li><a href="#about">about</a>
                    </li>
                    <li><a href="#features">features</a>
                    </li>
                    <li><a href="#reviews">reviews</a>
                    </li>
                    <li><a href="#screens">screens</a>
                    </li>
                    <li><a href="{% url 'public:signin' %}">sign in</a>
                    </li>
                    <li><a href="{% url 'public:signup' %}">sign up</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-->
</nav>